In [6]:
import tensorflow as tf
import pandas as pd
import matplotlib as plt
import numpy as np
import os
import scipy.io


In [27]:
#file = ("/Users/haseebshehzad/Desktop/Courses 1/Deep Learning/Project/MYPROJ/data/Cropped/train_32x32")
#data = np.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')

mat = scipy.io.loadmat('/Users/haseebshehzad/Desktop/Courses 1/Deep Learning/Project/MYPROJ/data/Cropped/train_32x32.mat')
imgs = mat['X']
labels = mat['y'].flatten()
#Return evenly spaced values within a given interval.
labels_one_hot = (np.arange(10) == labels[:, None]).astype(np.float32)
#converting images to arrays
rows = imgs.shape[0]
cols = imgs.shape[1]
chans = imgs.shape[2]
num_imgs = imgs.shape[3]
scalar = 1 / 255
# Note: not the most efficent way but can monitor what is happening
new_array = np.empty(shape=(num_imgs, rows, cols, chans), dtype=np.float32)
for x in range(0, num_imgs):
    # TODO reuse normalize_img here
    chans = imgs[:, :, :, x]
    # normalize pixels to 0 and 1. 0 is pure white, 1 is pure channel color
    norm_vec = (255-chans)* scalar
    # Mean Subtraction
    norm_vec -= np.mean(norm_vec, axis=0)
    new_array[x] = norm_vec

print (new_array)



[[[[  1.68504909e-01   1.67156860e-01   1.03431374e-01]
   [  1.51838228e-01   1.18749999e-01   1.15563728e-01]
   [  9.55882370e-02   8.59068632e-02   7.16911778e-02]
   ..., 
   [ -2.45098054e-04   1.09068630e-02   3.14950980e-02]
   [ -7.07107857e-02  -7.12009817e-02   2.63480395e-02]
   [ -1.10784315e-01  -8.57843161e-02   1.74019616e-02]]

  [[  1.88112751e-01   1.31862745e-01   1.15196079e-01]
   [  1.55759797e-01   1.10906862e-01   1.03799023e-01]
   [  9.95098054e-02   7.41421580e-02   7.95343146e-02]
   ..., 
   [  1.25245094e-01   1.12867646e-01   5.50245084e-02]
   [ -1.18872551e-02   3.30882357e-03   4.59558815e-02]
   [ -8.72549042e-02  -8.18627477e-02   1.34803923e-02]]

  [[  1.41053915e-01   1.24019608e-01   1.03431374e-01]
   [  1.40073523e-01   1.26593143e-01   8.81127417e-02]
   [  9.16666687e-02   8.59068632e-02   5.60049005e-02]
   ..., 
   [  1.91911772e-01   1.52083337e-01   7.46323541e-02]
   [  1.13602944e-01   6.60539195e-02   7.73284286e-02]
   [ -4.41176482e